name: Version Increment

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - run: git config --global user.name 'ryanmargono'
      - run: git config --global user.email 'ryantmargono@gmail.com'
      - run: npm version patch -m "[RELEASE] %s"
      - run: git push
